doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    migration_base_class: DoctrineMigrations\AbstractMigration
    storage:
        table_storage:
            table_name: migration_versions
    services:
        - '@doctrine.migrations.migration_factory'
