# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['https://arcadia-broceliande.netlify.app'] # Remplace par le domaine autorisé
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['content-type', 'authorization', 'x-auth-token']
        expose_headers: ['link']
        max_age: 3600
    paths:
        '^/api/':  # Appliquer ces règles à toutes les routes qui commencent par /api/
            allow_origin: ['https://arcadia-broceliande.netlify.app'] # Remplace par le domaine autorisé
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['content-type', 'authorization', 'x-auth-token']
            expose_headers: ['link']
            max_age: 3600
