# config/packages/nelmio_cors.yaml
# nelmio_cors:
#     defaults:
#         allow_origin: ['http://localhost:3000']
#         allow_credentials: true
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: []
#         allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
#         max_age: 3600
#     paths:
#         '^/api/': ~


        