# config/packages/security.yaml
security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            lazy: true
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
            custom_authenticator: App\Security\ApiTokenAuthentificatorAuthenticator

        

    access_control:
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/registration, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/avis, roles: PUBLIC_ACCESS }
        - { path: ^/api/role, roles: PUBLIC_ACCESS }
        - { path: ^/api/habitat, roles: PUBLIC_ACCESS }
        - { path: ^/api/nourriture, roles: PUBLIC_ACCESS }
        - { path: ^/api/service, roles: PUBLIC_ACCESS }
        - { path: ^/api/animal, roles: PUBLIC_ACCESS }
        - { path: ^/api/horaires, roles: PUBLIC_ACCESS }
        - { path: ^/api/image, roles: PUBLIC_ACCESS }
        - { path: ^/api/rapportveterinaire, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

